// Canonical AuditLog `action` values. Keep this list in sync with what's
// actually logged so the Activity Logs filter dropdown stays accurate.
module.exports = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  BRAND_CREATE: 'BRAND_CREATE',
  BRAND_UPDATE: 'BRAND_UPDATE',
  BRAND_DELETE: 'BRAND_DELETE',
  QUOTE_STATUS_UPDATE: 'QUOTE_STATUS_UPDATE',
  ENQUIRY_STATUS_UPDATE: 'ENQUIRY_STATUS_UPDATE',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  INVENTORY_STOCK_UPDATE: 'INVENTORY_STOCK_UPDATE',
  INVENTORY_AVAILABILITY_UPDATE: 'INVENTORY_AVAILABILITY_UPDATE',
};
